-- i write stuff here when i'm bored lmao

return {
	"This is some cool stuff man.";
	"omg so epik";
	"Slungus <33333333333";
	"If you bird up in ffa when you got torch or bird or judge im going to kill you";
	"Hey guys wanna bird up?";
	"Frick Win11";
	"Yo check out this funny video C://users//me//Videos//memez//AmpOO9KHU_uEALFU.mp4";
	"The factory must grow";
	"All my homies hate fake pngs";
	"Spoon";
	"I ate a tree";
	":3";
	"Play Crysis NOW!";
	"Play Half Life 1 - 2 NOW!";
	"Play Metro Exodus NOW!";
	"Play Mirrors Edge NOW!";
	"Play Entropy Zero 2 NOW!";
	"Play Portal 1-2 NOW!";
	"le fish";
	"I just bought this iphone off facebook marketplace and it got goole play on it, it's a fricking android bruh.";
	"Play Human Error Now! Oh wait that's not out yet, whoops";
	"when the";
	"fish";
	"cantaloupe";
	"Le bons way (real)";
	"Cool pc you got there!";
	"spongebob chair";
	"For a freeman, you seem to lack any freedom";
	"shoutout to Abstract 64!";
	"get jolly with it";
	"Check out FAMATTACK 2! https://www.youtube.com/watch?v=Ubne6jIx2dQ";
	"Wake up babe, a New Pyrocynical video dropped";
	"Scary fact number 67. There is a France.";
	"I'm going to take snaps, from snapchat, and burn them onto a dvd";
	"Vertex games please update Adventure Story!";
	"Are you guys going caroling?";
	"WOW!";
	"100% better than zloader";
	"Burger tank";
	"I could go for, bbq bacon burger,a large order of fries and orange soda with no ice and a piece of hot apple pie";
	"All these thoughts runnin' through my head";
	"Arms on fire, veins burnin' red";
	"Frustration is gettin' bigger";
	"Bang Bang Bang -- Pull my Devil Trigger!";
	"micro/kick/self/Mass kill";
	"Reszta Ne Rozumiju";
	"At indigo park";
	"Skibidi logger enabled...";
	"You are my speical";
	"Check out renoise";
	"HN IS OVERRATED!!!!!";
	"With this treasure, I summon...";
	"You are now breating manually.";
	"Cause it feels so empty without me.";
	"NO, THIS IS PATRICK";
	"erm";
	"[Errorcodedot] do NOT run funny \n [pointypease668] r/funny";
	"Damn son, where'd you find that";
	"Hold up";
	"*Amen break*";
	"What are you doing? Eh, just some jujutsu shenanigans.";
	"Mahito worm";
	"Jogobela";
	"Damn Daniel";
	"woah i";
	"He ate 71 pounds of sand and died";
	"My studens are ALL MORONS!";
	"Dude it says subscribe if you like farts, bro how could it possibly be inapropriate";
	"Milions of players are doing the stupidest stuff on roblox.";
	"Dawg i need to get spotify premium :sob:";
	"Yolo fellow kids";
	"You know what that means";
	"Sippin' on straight chlorine";
	"Based? Based on what?";
	"Half Life? Why not the full one";
	"Cancel Cultrue? Why? Culture is so beautiful!";
	"Watch yo tone";
	"Aren't you Nathaneil B?";
	"Shiii bro im finna go sleep";
	"I am on my way! My heart is racing with excitement, my soul is ablaze with determination. Every step I take brings me closer to you. Nothing can stop me now. I will traverse mountains, cross oceans, and break through any obstacle in my path to reach you. Just wait for me, my love, for I am coming for you with fierce passion and unwavering devotion. Our reunion will be a celebration of love that knows no bounds. Oh, my darling, I am on my way to you! -- made by ai btw when formalazing 'omw'";
}
